export const DRIVER = 'Driver'
export const EATS = 'Eats'
export const LEISURE = 'Leisure'
export const GAME_OVER = 'Game Over'
export const BERKELEY = 'Berkeley'
export const SAN_FRANCISCO = 'San Francisco'
export const LEISURE_TIMEOUT = 5;
export const BUTTON_TIMEOUT = 5;
export const TOTAL_TIME = 1600;